apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    environment: Dev
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort 
  selector: #below are lables from above pod 
    environment: dev
    app: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 # this port belogs to service
    targetPort: http-web-svc # this port belongs to container