apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels: # these lebels are replicaset labels, every k8s resourcce have labels. 
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # these labels should match with pod labels
      tier: frontend
      app: nginx 
      environment: dev
  template: # this one is nothing but pod defination, pod is subset of replicaset. 
    metadata:
      labels: # these are the pod labels 
        tier: frontend
        app: nginx 
        environment: dev 
    spec:
      containers:
      - name: nginx 
        image: nginx 
