apiVersion: v1
kind: Pod
metadata: 
  name: simple-pod # this is name of the pod
#if you dont mention specific namespace, if you dont give this it will attach to the default
  namespace: roboshop
spec:
  containers:
  - name: nginx-simple # this name of the container
    image: nginx:1.14.2
    # Ports are mandatory thing because it will open ports autometiclaly
    ports:
    - containerPort: 80 
    
