apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec: 
  containers:
  - name: nginx
    image: nginx
  - name: sidecar
    image: almalinux:8
    #almalinux will be available for 200 seconds to login to container
    command: ["sleep", "200"]

    
  


