apiVersion: v1
kind: secret
metadata:
  name: secret-basic-auth
data:
  username: cHJhdmVlbgo= 
  password: ZGV2b3BzMTIzCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: config-pod-direct
    image: nginx
    envFrom: 
    - secretRef: 
        name: secret-basic-auth